### ISSUE TITLE
kl divergence increase?

### ISSUE THREAD

**Issue by wangzheallen** [nicola-decao/s-vae#1]
Hi,

I ran the example code but found the kl divergence increases(I think should decrease?) with the training going and reconstruction loss decreasing (should be correct),

could you please help explain?

**Comment by nicola-decao** [comment]
Hi,

Have you just run the example or have you changed something (e.g, epochs)? Can you be more precise?

Remind that in general, there is no guarantee about KL convergence. In VAEs, only the ELBO is maximized and should increase with training.

**Comment by wangzheallen** [comment]
yeah, I ran the example again, and did not change anything. the ELBO is increasing, reconstruction loss decreasing and the KL increase
